### ISSUE TITLE
Unable to login as admin

### ISSUE THREAD

**Issue by vikram-ray** [Patrowl/PatrowlHears#162]
I tried to start the server with docker - 
1. git clone https://github.com/Patrowl/PatrowlHears
2. cd PatrowlHears
3. docker-compose up

then opened my browser on http://localhost:8383/ and tried logging in with
default username: admin
default password: Bonjour1!

but getting 500 error and not able to login - 
![image](https://user-images.githubusercontent.com/22349420/175820693-196de17c-a479-4617-8ad4-1ce7296ad129.png)
![image](https://user-images.githubusercontent.com/22349420/175820738-edea766b-e36f-4fa2-837e-88d068b6bdea.png)

I even created a new superuser but got the same authentication error; Any help would be appreciated.

**Comment by doctorPrinz** [comment]
I am getting the same error

**Comment by tracid56** [comment]
Hello !
Same issue here :c

**Comment by AntoninHL** [comment]
Same for me...
and no idea how to solve this issue...

**Comment by MaKyOtOx** [comment]
Hi @all, thank you for the issue. We have reproduced the issue. Will be fixed in first week of september
