### ISSUE TITLE
Unable to login as admin

### ISSUE THREAD

**Issue by AntoninHL** [Patrowl/PatrowlHears#167]
Hello all!

I just reinstall my Hears server, but I can't first login with admin account...

Really strange error related to ADFS attribute...

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/50768/185389617-89cfcfc5-3548-4e6b-aef8-45713f85369f.png">

Any idea?

**Config:**

- VPS - 8Go RAM - 160 Go storage
- Ubuntu 20.04
- Docker

Thanks

Antonin

**Comment by MaKyOtOx** [comment]
Hi @AntoninHL 
The issue is in the default settings regarding the latest support of ADFS authentication. Will be fixed soon :)

**Comment by MaKyOtOx** [comment]
Seems to be fixed. We have still issues in PatrowlHearsData (files too big) to have latest updates. Will be soon fixed
