### ISSUE TITLE
[Feature Request] PatrowlHears on DockerHub

### ISSUE THREAD

**Issue by david-colombo** [Patrowl/PatrowlHears#36]
I'd love, if you could put the PatrowlHears Docker image on DockerHub.
Thanks in advance!

**Comment by MaKyOtOx** [comment]
Hello @david-colombo 
The Docker image is already on DockerHub: https://hub.docker.com/r/patrowl/patrowl-hears-community-edition/
Try this:
`docker pull patrowl/patrowl-hears-community-edition:latest`

By the way, it won't work without nginx, postgres and rabbitmq side-kicks: -> use the docker-compose file instead for a quick installation

NB: python requirements fix available in v1.0.2 :)

**Comment by MaKyOtOx** [comment]
upload of v1.0.2 docker image in progress :)

**Comment by MaKyOtOx** [comment]
done -> version 1.0.2 is now available on DockerHub https://hub.docker.com/r/patrowl/patrowl-hears-community-edition/

Installation and DB update steps available here: https://github.com/Patrowl/PatrowlHears/blob/master/INSTALL.md

Any feedbacks are welcome :)

**Comment by david-colombo** [comment]
Thanks very much for the clarification and the docker image update! :D
