### ISSUE TITLE
[FEATURE REQ] Import Monitor List(s)

### ISSUE THREAD

**Issue by nin-ack** [Patrowl/PatrowlHears#41]
Having **the ability to import lists of various things to be monitored via a standard format e.g. JSON**, would be extremely beneficial. Rather than scrolling through the lists and/or having to manually add them on the backend, this would be much more convenient.

**Comment by nin-ack** [comment]
Looks like this feature is already a thing and I missed it 👍

**Comment by MaKyOtOx** [comment]
Yes, you got it :)
