### ISSUE TITLE
swagger configuration

### ISSUE THREAD

**Issue by SPoint42** [Patrowl/PatrowlHears#43]
There is 2 problems noticed after a few tests : 

1. **Try out does not take the port of the server:** 

When trying to play with the Try it out on the swagger, I got an unexcpeted error. 

This seem that the swagger doesnt take care of the port where running the patr0wlHears
I launch the docker on the 8383 port, and when try to fetch I got in the swagger extract : 
```
Request URL
http://xxx.xxxx.xxx.xxx/api/alerts/ 
```

and not 
```
Request URL
http://xxx.xxxx.xxx.xxx:8383/api/alerts/ 
```

as said in : https://stackoverflow.com/a/59457975/4086042

this seem to be a configuration error

2.**It's not possible to try with a API Key**

**Comment by MaKyOtOx** [comment]
Hello @SPoint42 !
I think 1. is an issue with the nginx configuration too. Try with the Django application port (TCP/8083?). In a dockerized deployment, you would need to expose it first :)
