### ISSUE TITLE
[Alerts] Alerts don't go out to Slack

### ISSUE THREAD

**Issue by robben-ar** [Patrowl/PatrowlHears#75]
Hi! I have problem to send alert to slack

I tried configuring the 'backend_app/backend_app/settings.py' the api-token and the webhook by the GUI 'Slack alerting' but the alert does not arrive on slack channel
![image](https://user-images.githubusercontent.com/16881807/115874837-f7e4bd00-a41a-11eb-8677-6a0f1ac05435.png)

Also probe generate this task via api so that it sends via slack the alert but it does not arrive
![image](https://user-images.githubusercontent.com/16881807/115874811-f0251880-a41a-11eb-8628-ea8ff459f782.png)

Thank you very much for sharing this project with the community.

**Comment by robben-ar** [comment]
I keep getting the same error sending an alert to Slack.
![image](https://user-images.githubusercontent.com/16881807/122933763-4e03ad00-d345-11eb-84ed-a362d5dd13d0.png)

Try to send via web and console but it does not arrive, example:
`curl 'http://192.168.1.20:8383/api/vulns/admin/slack-alert/PH-145340' -H "accept: application/json" -H  "X-CSRFToken: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" -H 'Authorization: Token XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'`

or

http://192.168.1.20:8383/api/alerts/vuln/PH-165170/slack
 
- Where do I declare the 'django.conf'?
- Is this feature functional? And the email works?

Thanks.-

**Comment by Ankirama** [comment]
Hey,
I had some issues with slack too, but I could fix it after some debug!

Here what I did:

Firstly you will need to set your Slack webhook in settings / alerting (https://patrowlhears.domain.tld/#/settings): https://hooks.slack.com/services/XXX/XXX/XXX

Here the real issue: **SLACK ALERTS ARE DISABLED BY DEFAULT** 💥 You will need to enable them in the admin panel in **Org settingss** (https://patrowlhears.domain.ltd/admin/users/orgsettings/).

You must check `Alerts slack enabled` and your issues will be fixed :)

I will try to create a PR to fix this issue.

Have fun!
