### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by sdmzn** [Patrowl/PatrowlHears#92]
the default accounts are not being accepted when installing using installation script, is there any way to reset the password from console?

**Comment by MaKyOtOx** [comment]
Hi, weird :/
You can reset the user password using Django:
```
[source env/bin/activate]
python manage.py changepassword admin
```

Note: Did you create the user before ? how did you installed the tool ?

**Comment by MaKyOtOx** [comment]
up ?
